# ----
# Site

title: WRules
description: WRules Jekyll template.
url: https://wrules.github.io/wp/
permalink: pretty

# -----
# Build

timezone: Etc/UTC
collections:
  documentation:
    title: Welcome
    position: 1
  html:
    title: HTML
    position: 2
  api:
    title: API
    position: 3
  ajax:
    title: AJAX
    position: 4
  css:
    title: CSS
    position: 5
  javascript:
    title: JavaScript
    position: 6
  git:
    title: Git
    position: 7
  gulp:
    title: Gulp
    position: 8
  linux:
    title: Linux
    position: 9
  php:
    title: PHP
    position: 10
  mysql:
    title: MySQL
    position: 11
  seo:
    title: SEO
    position: 12
  wordpress:
    title: WordPress
    position: 13
  webpack:
    title: Webpack
    position: 14  
  lint:
    title: Lint
    position: 15                             
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "documentation"
    values:
      _hide_content: true
  -
    scope:
      type: "html"
    values:
      _hide_content: true

# -----------

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css