# ----
# Site

title: WRules
description: WRules Jekyll template.
url: https://wrules.github.io/wp/
permalink: pretty

# -----
# Build

timezone: Etc/UTC
collections_dir: categories
collections:  
  documentation:
    title: Welcome
    position: 1
  api:
    title: API
    position: 2
  ajax:
    title: AJAX
    position: 3
  css:
    title: CSS
    position: 4
  html:
    title: HTML
    position: 5
  javascript:
    title: JavaScript
    position: 6
  git:
    title: Git
    position: 7
  gulp:
    title: Gulp
    position: 8
  linux:
    title: Linux
    position: 9
  php:
    title: PHP
    position: 10
  mysql:
    title: MySQL
    position: 11
  seo:
    title: SEO
    position: 12
  wordpress:
    title: WordPress
    position: 13
  webpack:
    title: Webpack
    position: 14  
  lint:
    title: Lint
    position: 15                             
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "documentation"
    values:
      _hide_content: true
  -
    scope:
      type: "api"
    values:
      _hide_content: true

# -----------